title: My Minimal Template
description: Jekyll + Tailwind + Alpine
baseurl: "" 
url: ""

markdown: kramdown
theme: null # Set to null since we are building custom HTML layouts

# CRUCIAL: Tell Jekyll to completely ignore these folders
exclude:
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js